version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: ["pgdata:/var/lib/postgresql/data"]
    ports: ["5432:5432"]

  redis:
    image: redis:7
    volumes: ["redisdata:/data"]
    ports: ["6379:6379"]

  backend:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    depends_on: [db, redis]
    ports: ["4000:4000"]

  frontend:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on: [backend]
    ports: ["3000:3000"]

volumes:
  pgdata:
  redisdata:
