services:
  backend:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.backend.prod
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.frontend.prod
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"
